In [22]:
import torch

In [41]:
id2word = {
    0: "hello",
    1: "world",
    2: "cat",
    3: "dog",
    4: "apple"
}
word2id = {v:k for k,v in id2word.items()}
input_ids = torch.tensor([i for i in range(0,5)])

In [33]:
#vector dim = 3

embedding_layer = torch.nn.Embedding(num_embeddings=len(input_ids),embedding_dim=4)


In [37]:
embedding_layer.weight

Parameter containing:
tensor([[ 0.4079,  0.6511, -0.2084,  2.1414],
        [ 0.2596, -0.6017, -1.7448, -0.5529],
        [-1.2867,  1.1880,  1.4548,  0.1485],
        [ 0.0150,  0.1874, -1.5304, -1.4819],
        [ 0.6921,  0.3553,  1.8823,  1.0843]], requires_grad=True)

In [42]:
embedding_layer(torch.tensor(word2id["apple"]))

tensor([0.6921, 0.3553, 1.8823, 1.0843], grad_fn=<EmbeddingBackward0>)

In [43]:
embedding_layer(torch.tensor([word2id["apple"],word2id["dog"]]))

tensor([[ 0.6921,  0.3553,  1.8823,  1.0843],
        [ 0.0150,  0.1874, -1.5304, -1.4819]], grad_fn=<EmbeddingBackward0>)