In [ ]:
!pip install torch

###Implementing Simplified attention mechanism
####consider following input sequencce as our embedding vector

In [33]:
import torch

inputs = torch.tensor([
    [0.43, 0.15, 0.891],  # "Your"
    [0.55, 0.87, 0.66],   # "journey"
    [0.57, 0.85, 0.641],  # "starts"
    [0.22, 0.58, 0.331], # "with"
    [0.77, 0.25, 0.101],  # "one"
    [0.05, 0.80, 0.551]   # "step"
])

print(inputs.shape)


torch.Size([6, 3])


In [34]:
#lets take journey and calculate attention weights with rest of them

query = inputs[1]
attention_weights = torch.empty(inputs.shape[0])
for i,x_i in enumerate(inputs):
  attention_weights[i] = torch.dot(x_i,query)
attention_weights

tensor([0.9551, 1.4950, 1.4761, 0.8441, 0.7077, 1.0872])

In [35]:
#lets calculate attention weights for all

query = inputs[1]
attention_weights = torch.empty(inputs.shape[0])
for i,x_i in enumerate(inputs):
  attention_weights[i] = torch.dot(x_i,query)
attention_weights

tensor([0.9551, 1.4950, 1.4761, 0.8441, 0.7077, 1.0872])

In [36]:
#we got attention weights for all queries
attention_weights = inputs @ inputs.T
attention_weights

tensor([[1.0013, 0.9551, 0.9437, 0.4765, 0.4586, 0.6324],
        [0.9551, 1.4950, 1.4761, 0.8441, 0.7077, 1.0872],
        [0.9437, 1.4761, 1.4583, 0.8306, 0.7161, 1.0617],
        [0.4765, 0.8441, 0.8306, 0.4944, 0.3478, 0.6574],
        [0.4586, 0.7077, 0.7161, 0.3478, 0.6656, 0.2942],
        [0.6324, 1.0872, 1.0617, 0.6574, 0.2942, 0.9461]])

In [37]:
import torch.nn.functional as F
# apply softmax along last dimension (rows)
softmaxed = F.softmax(attention_weights, dim=-1)

In [38]:
context_vectors = softmaxed@inputs

In [39]:
context_vectors

tensor([[0.4420, 0.5930, 0.5798],
        [0.4418, 0.6514, 0.5691],
        [0.4431, 0.6496, 0.5679],
        [0.4304, 0.6298, 0.5519],
        [0.4671, 0.5910, 0.5275],
        [0.4177, 0.6503, 0.5654]])

In [ ]:
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

words = ["Your", "journey", "starts", "with", "one", "step"]

fig = plt.figure(figsize=(8, 6))
ax = fig.add_subplot(111, projection='3d')

for i, vec in enumerate(context_vectors):
    ax.scatter(vec[0], vec[1], vec[2], label=words[i])
    ax.text(vec[0], vec[1], vec[2], words[i])  # label point

ax.set_xlabel('X')
ax.set_ylabel('Y')
ax.set_zlabel('Z')
ax.set_title("Context Vectors (3D)")
plt.legend()
plt.show()
